### ISSUE TITLE
receiving error ""error": { "name": "instanceNotFoundError", "message": "We could not find the collection you are looking for"" while checking verify your work

### ISSUE THREAD

**Issue by speeta137** [vdespa/automation-with-postman-course#10]
I have made sure that there were no gaps in the ID while passing. Could you please help me in this.
<img width="959" alt="Screenshot 2024-11-10 220415" src="https://github.com/user-attachments/assets/2ce1d53f-be68-45ee-9aba-9b71c2a3aae3">

<img width="959" alt="image" src="https://github.com/user-attachments/assets/ad08c25d-b058-4fd7-ba68-3f03fdc08477">

**Comment by vdespa** [comment]
If you call the collections/ endpoint, do you see your collection id in the list?

**Comment by speeta137** [comment]
yes
![image](https://github.com/user-attachments/assets/5ee58afe-8abc-4f22-908e-253fcbd1846c)

**Comment by vdespa** [comment]
Can you send me a screenshot of the response of the collections/ endpoint where the collection Id is visible in the response?

**Comment by speeta137** [comment]
NO, collection ID is not visible in the response

**Comment by speeta137** [comment]
<img width="959" alt="image" src="https://github.com/user-attachments/assets/62e0c011-50a1-45fb-834a-e6a5cac876f4">
Why am I getting assignment 2 response for Assignment 1 request

**Comment by vdespa** [comment]
Check the value of the collectionId. It needs to be updated to the current collection.
