### ISSUE TITLE
Status 401 and error message saying : Missing API key - though API key generated and used

### ISSUE THREAD

**Issue by suvechha** [vdespa/automation-with-postman-course#2]
Hi Valentin, I have getting Status 401 
though I have generate API key from my profile and assign it to the postman_api_key under the Assignment 1 collection. What I am doing wrong .? Please suggest

![Screen Shot 2023-08-16 at 13 55 02](https://github.com/vdespa/automation-with-postman-course/assets/4578336/3762a332-e5a0-4ce9-ad1d-b19347e9378a)
![Screen Shot 2023-08-16 at 13 55 33](https://github.com/vdespa/automation-with-postman-course/assets/4578336/816fad72-5e0f-4869-96d1-67302c415f6e)

**Comment by vdespa** [comment]
Without seeing the request, it is hard to tell.

**Comment by suvechha** [comment]
Here is the request
![Screen Shot 2023-08-17 at 11 35 03](https://github.com/vdespa/automation-with-postman-course/assets/4578336/287e4c83-7780-4dfd-9bf4-af72d33f0dc6)

**Comment by vdespa** [comment]
Where did you put your API key? I can't see this from the screenshot.
