### ISSUE TITLE
Assignment #2: Getting 'expected undefined to be an object' error

### ISSUE THREAD

**Issue by Ciiku-Kihara** [vdespa/automation-with-postman-course#5]
Hello,

I am currently working on assignment 2. I have followed all instructions(making a copy of the requests, adding the tests and adding the copies to the API Requests folder) but I am getting a 'expected undefined to be an object' error for all my tests. I am not sure what I am missing at this point. Could you help me out? 

![image](https://github.com/vdespa/automation-with-postman-course/assets/77234925/95786c49-a5d4-4900-87bc-8a488129377f)

**Comment by vdespa** [comment]
Hard to tell what the issue is. Can you share your workspace link?

**Comment by Ciiku-Kihara** [comment]
Sure! Here's the link: https://app.getpostman.com/join-team?invite_code=ba9f1081027e4ab980240e2faef45841&target_code=a35cb814f2f0c66a053269d6222e47b5

**Comment by vdespa** [comment]
This needs to be in a public workspace.
