### ISSUE TITLE
Postman API Test Automation for Beginners (FreeCodeCamp)- API down

### ISSUE THREAD

**Issue by ClaudiaK1056** [vdespa/automation-with-postman-course#6]
I'm taking the Postman API Test Automation for Beginners (FreeCodeCamp) from you tube
I was able to run tests last week but after a reboot this week I'm receiving an errror.
I forked the collection Valentino Artisan Coffee House API.
Clicked on Get API status
The following error was displayed
Error: Tunneling socket could not be established - Status code= 407

After a few minutes I'm not getting the following error 
I'm getting an error - Could not send request
SSL Error: Unable to verify the first certificate- Disable SSL Verification
Screenshot attached

![image](https://github.com/vdespa/automation-with-postman-course/assets/115257013/d466e5d2-ca73-4bf7-866a-07d628cc6eb7)

**Comment by vdespa** [comment]
Did you try to run the request from your browser by going to postman.com and opening the collection there?

**Comment by ClaudiaK1056** [comment]
That was it.. the API is now showing up and running.
Thank you for your fast reply. BTW the course is great!
