### ISSUE TITLE
Invalid API key error

### ISSUE THREAD

**Issue by josep1994** [vdespa/automation-with-postman-course#7]
Hi, 

I am getting an invalid API key error for get and post requests for Orders and Products APIs. I tried all the steps you mentioned in the course right from the beginning but still got the error. Please help.
The API key seen in the below screenshot is newly generated and copy pasted immediately.

![image](https://github.com/vdespa/automation-with-postman-course/assets/166456402/9c50e738-4b08-41e6-9f2e-9d83da92e41c)

**Comment by vdespa** [comment]
Yeah, that definitely does not look like a valid key for this API. That's a Postman API key. 

Try rewatching the respective lectures.
