### ISSUE TITLE
Assignment1: Getting error "instanceNotFoundError" while running the 'Verify your work' request.

### ISSUE THREAD

**Issue by nits2612** [vdespa/automation-with-postman-course#8]
I am getting the below error message when trying to verify work. Also I have the collection id stored in my variables section for Assignment 1.

```
>   "error": {
>         "name": "instanceNotFoundError",
>         "message": "We could not find the collection you are looking for"
>     }
```

Please find below screenshots:

<img width="632" alt="image" src="https://github.com/vdespa/automation-with-postman-course/assets/54543030/582a8859-fe78-4e4d-adbd-9148267bf6ff">

<img width="624" alt="image" src="https://github.com/vdespa/automation-with-postman-course/assets/54543030/e0f4e231-8c3d-478c-aef7-8dbbe591687f">

**Comment by nits2612** [comment]
I am using the same collection id as assignment 1 collection:
<img width="614" alt="image" src="https://github.com/vdespa/automation-with-postman-course/assets/54543030/709f24ec-0a0a-4a44-ba39-e6bac3323588">

**Comment by vdespa** [comment]
What do you see if you call only the /collections/ endpoint without specifying a collection id?

**Comment by nits2612** [comment]
If I remove the collection id from variable section in the collection, then I am getting the below response.
Also there are other responses too regarding my other collections too which which are in other workspace.

 {
            "id": "159e3e7d-0feb-4fb3-8fda-c2fc1cd2586c",
            "name": "✅ Assignment #1",
            "owner": "3278242",
            "createdAt": "2024-05-30T13:34:07.000Z",
            "updatedAt": "2024-05-30T14:00:03.000Z",
            "uid": "3278242-159e3e7d-0feb-4fb3-8fda-c2fc1cd2586c",
            "fork": {
                "label": "Nityanand Ghosh's fork",
                "createdAt": "2023-05-07T19:32:47.000Z",
                "from": "2354738-686451d7-0345-4620-9c2e-f3b936807a4e"
            },
            "isPublic": false

**Comment by vdespa** [comment]
Can you check again your request in the Postman console? You might have a new line or a space at the end of the value for the collection id.

**Comment by nits2612** [comment]
Yes, indeed there was a space in collection id in Variable section of collection. I don't know how did it came up while copy and pasting.
Thank you so much for your help. Really appreciated.
