### ISSUE TITLE
401 Unauthorized in assignment Three.

### ISSUE THREAD

**Issue by Mirza-Raiyan-Ahmed** [vdespa/automation-with-postman-course#9]
Hello, I followed everything as per video but the output is saying that "Missing API Key". and the test  passes, one of the two test. It passed only the "Response body is JSON",on the other hand,it fails 
![Test Results](https://github.com/user-attachments/assets/4cb2c4cf-b115-4d31-8110-dec54b85c633).

I am also attaching the Code Snippets from "Create a New Order "

![Pre Request](https://github.com/user-attachments/assets/a5a994ec-a548-43e1-b577-5c869bf0e21c)
![Post Request](https://github.com/user-attachments/assets/41b2a09a-08c1-4195-afab-eb602e7df75a)
![Code Output Body](https://github.com/user-attachments/assets/b0c0754a-c900-425c-ac76-3f02373892d8)
 
 
 I have been trying to resolve the issue for 2 days but failed. Please look onto it on your earliest Concern.

**Comment by vdespa** [comment]
I can't see from the screenshots where you provided the API key. Maybe you can provide an additional screenshot. Thanks.

**Comment by sh0tal** [comment]
i have the same issue on assignment 3. I added the postman api key in the collection just like the previous ones and also the collection_uuid and when i try to send the GET request i get error 401: Missing API key
![image](https://github.com/user-attachments/assets/1896a3d2-3e23-4495-b378-d5d1b267411d)


i managed to find the issue but not yet solve it. Basically when you dublicate the request to add in the API requests folder of the 3rd assignment, it gets dublicated but the x-api-key header is missing. I added it manual but now i am receiving an authorization 403, "error": "Invalid API key"
When i try to print it in the console:console.log(pm.environment.get("apiKey"));
 i am getting undefined.

**Comment by vdespa** [comment]
I think you are confusing the API keys... The Postman API key is one thing, the Coffee House API key is another. 

In the screenshot, it looks like you are calling the Coffee House API, not the Postman API.

**Comment by sh0tal** [comment]
Hello @vdespa ,

Okay i see what you are talking about.
So, what's the problem with my request? i mean where do i put the API key from the coffee house api to the request?
On the original collection we stored the token in the variables of the collection. Now where do i have to add it in regards to the Assignment 3 collection?
Because the rest of the assignments i didn't have such a problem.

**Comment by Mirza-Raiyan-Ahmed** [comment]
Hello,

I have attached all the screenshot with this email.

Please Find attached the screenshots.

Regards,

Mirza Raiyan Ahmed

**Comment by vdespa** [comment]
Please check the API documentation.
If you are submitting a request as part of the assignment, follow the instructions from the collection.

For additional help, please use the Postman community forum.
 
Thank you for understanding.
